repos:
  # Pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-format
        exclude: '.*/migrations/.*'
      - id: ruff-check
        args: [--fix]
        exclude: '.*/migrations/.*'
