[project]
name = "udnnews"
version = "0.1.0"
description = "Unnotech Backend Engineer Coding Test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.2",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.13.0",
    "gunicorn>=25.1.0",
    "psycopg[binary]>=3.3.3",
    "scrapy>=2.14.1",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pyright>=1.1.408",
    "ruff>=0.15.4",
]
