# Generated by Django 5.2 on 2026-02-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story_id", models.CharField(max_length=20, unique=True)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "focus_title",
                    models.CharField(
                        blank=True,
                        help_text="Title as shown in the index page focus block; may differ from the article page title.",
                        max_length=500,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("body", models.JSONField(default=list)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="news.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="news_articl_publish_62720b_idx"
                    ),
                    models.Index(
                        fields=["category"], name="news_articl_categor_ac462d_idx"
                    ),
                ],
            },
        ),
    ]
